import { NextResponse } from 'next/server';
import { getMembership, getUserFromSession } from '@/lib/auth';
import { cookies } from 'next/headers';
import { supabaseAdmin } from '@/lib/supabaseAdmin';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

type SectionInput = { id?: string; name: string; sortOrder?: number; masterPlanUrl?: string | null; droneUrl?: string | null };
type LotInput = { id?: string; number: string; status?: string; owner?: string; price?: number | string | null; area?: number | string | null; direction?: string; model?: string; points?: string; labelX?: number; labelY?: number; geometrySource?: string; sectionId?: string | null };
type Project = { id: string; slug: string; name: string; created_by: string };
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
function normalizeSlug(value:string){return value.toLowerCase().replace(/[^a-z0-9]/g,'')}
function planLabel(planType:string){if(planType==='master_plan')return 'Master';const m=planType.match(/^section_(\d+)$/);return m?`Section ${m[1]}`:planType}
async function findProject(slug:string):Promise<Project|null>{const db=supabaseAdmin();const {data:exact,error:ee}=await db.from('projects').select('id,slug,name,created_by').eq('slug',slug).maybeSingle();if(ee)throw ee;if(exact)return exact;const {data,error}=await db.from('projects').select('id,slug,name,created_by');if(error)throw error;return(data||[]).find(p=>normalizeSlug(p.slug)===normalizeSlug(slug))||null}
async function requireAdmin(slug:string){const token=(await cookies()).get('landgrid_user')?.value;const user=await getUserFromSession(token);if(!user)return{error:NextResponse.json({error:'Unauthorized'},{status:401})};const project=await findProject(slug);if(!project)return{error:NextResponse.json({error:'Project not found'},{status:404})};const role=await getMembership(user.id,project.slug);if(role!=='admin'&&project.created_by!==user.id)return{error:NextResponse.json({error:'Admin access required'},{status:403})};return{user,project}}
export async function GET(_req:Request,{params}:{params:Promise<{slug:string}>}){try{const{slug}=await params;const project=await findProject(slug);if(!project)return NextResponse.json({error:'Project not found'},{status:404});const db=supabaseAdmin();const {data:plans,error:pe}=await db.from('project_site_plans').select('id,project_id,plan_type,map_url,drone_url,created_at,updated_at').eq('project_id',project.id).order('plan_type');if(pe)throw pe;const sections=(plans||[]).map(p=>({id:p.plan_type,name:planLabel(p.plan_type),sortOrder:p.plan_type==='master_plan'?0:Number(p.plan_type.match(/^section_(\d+)$/)?.[1]||999),masterPlanUrl:p.map_url,droneUrl:p.drone_url}));const {data:plots,error:le}=await db.from('plots').select('id,plot_number,status,owner,price,area_sq_yards,area_sq_ft,direction,details,geometry,section').eq('project_id',project.id).order('plot_number');if(le)throw le;return NextResponse.json({project:{id:project.id,slug:project.slug,name:project.name},sections,lots:(plots||[]).map(plot=>({id:plot.id,number:plot.plot_number,status:plot.status||'available',owner:plot.owner||'',price:plot.price,area:plot.area_sq_yards??plot.area_sq_ft??null,direction:plot.direction||'',model:plot.details||'',points:typeof plot.geometry==='string'?plot.geometry:String((plot.geometry as any)?.points||''),labelX:Number((plot.geometry as any)?.labelX||0),labelY:Number((plot.geometry as any)?.labelY||0),geometrySource:(plot.geometry as any)?.geometrySource||'database',sectionId:plot.section||sections[0]?.id||null}))},{headers:{'Cache-Control':'no-store'}})}catch(error){console.error('[plan-get]',error);return NextResponse.json({error:'Unable to load project plan'},{status:500})}}
export async function POST(req:Request,{params}:{params:Promise<{slug:string}>}){try{const{slug}=await params;const auth=await requireAdmin(slug);if('error'in auth)return auth.error;const body=await req.json().catch(()=>({}));const sections=Array.isArray(body.sections)?body.sections as SectionInput[]:[];const lots=Array.isArray(body.lots)?body.lots as LotInput[]:[];if(!sections.length)return NextResponse.json({error:'At least one plan is required'},{status:400});const db=supabaseAdmin();const persisted:any[]=[];for(const section of sections){const name=String(section.name||'').trim();const requested=String(section.id||'').trim().toLowerCase();const fromName=name.toLowerCase().match(/^section\s+(\d+)$/);const planType=requested==='master_plan'||requested==='master'?'master_plan':/^section_\d+$/.test(requested)?requested:fromName?`section_${fromName[1]}`:'';if(!planType)continue;const {data,error}=await db.from('project_site_plans').upsert({project_id:auth.project.id,plan_type:planType,map_url:section.masterPlanUrl??null,drone_url:section.droneUrl??null},{onConflict:'project_id,plan_type'}).select('id,plan_type,map_url,drone_url').single();if(error)throw error;persisted.push(data)}
const valid=new Set(persisted.map(p=>p.plan_type));const fallback=persisted.find(p=>p.plan_type==='master_plan')?.plan_type||persisted[0]?.plan_type||null;
const clean=(v:unknown)=>{if(v===''||v==null)return null;const n=Number(v);return Number.isFinite(n)?n:null};
const incomingIds=new Set<string>();let created=0,updated=0;
for(const lot of lots){const sectionId=valid.has(String(lot.sectionId||''))?String(lot.sectionId):fallback;if(!sectionId)continue;const payload={project_id:auth.project.id,plot_number:String(lot.number||''),status:lot.status||'available',owner:lot.owner||null,price:clean(lot.price),area_sq_yards:clean(lot.area),direction:lot.direction||null,details:lot.model||null,geometry:{points:String(lot.points||''),labelX:Number(lot.labelX||0),labelY:Number(lot.labelY||0),geometrySource:lot.geometrySource||'manual'},section:sectionId};let existing:any=null;if(lot.id&&UUID.test(lot.id)){const {data}=await db.from('plots').select('id').eq('id',lot.id).eq('project_id',auth.project.id).maybeSingle();existing=data}if(existing)incomingIds.add(existing.id);if(existing){const {error}=await db.from('plots').update(payload).eq('id',existing.id);if(error)throw error;updated++}else{const {data,error}=await db.from('plots').insert(payload).select('id').single();if(error)throw error;if(data)incomingIds.add(data.id);created++}}
const {data:existingRows,error:existingError}=await db.from('plots').select('id').eq('project_id',auth.project.id);if(existingError)throw existingError;const deletedIds=(existingRows||[]).map(r=>r.id).filter(id=>!incomingIds.has(id));if(deletedIds.length){const {error}=await db.from('plots').delete().eq('project_id',auth.project.id).in('id',deletedIds);if(error)throw error}
return NextResponse.json({ok:true,sections:persisted.length,lots:lots.length,createdPlots:created,updatedPlots:updated,deletedPlots:deletedIds.length})}catch(error){console.error('[plan-save]',error);return NextResponse.json({error:error instanceof Error?error.message:'Unable to save project plan'},{status:500})}}