"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { FolderOpen, Plus, ArrowRight, X } from "lucide-react";

type Project = { id: string; slug: string; name: string; address: string; description?: string | null; role: "admin" | "sales" };
const btn: React.CSSProperties = { border: "1px solid #dce3df", background: "white", color: "#17211b", padding: "10px 14px", borderRadius: 9, fontWeight: 750, cursor: "pointer", display: "inline-flex", alignItems: "center", justifyContent: "center", gap: 7 };

export default function Projects() {
  const [projects, setProjects] = useState<Project[]>([]), [loading, setLoading] = useState(true), [creating, setCreating] = useState(false), [showCreate, setShowCreate] = useState(false), [error, setError] = useState("");
  const [form, setForm] = useState({ name: "", address: "", googleLocationUrl: "", description: "" });
  async function load() { setLoading(true); setError(""); try { const r = await fetch("/api/projects", { cache: "no-store" }); const d = await r.json(); if (!r.ok) throw new Error(d.error || "Unable to load projects"); setProjects(d.projects || []); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load projects"); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  async function create(e: React.FormEvent) { e.preventDefault(); setCreating(true); setError(""); try { const r = await fetch("/api/projects", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const d = await r.json(); if (!r.ok) throw new Error(d.error || "Unable to create project"); window.location.href = `/projects/${d.project.slug}/editor`; } catch (e) { setError(e instanceof Error ? e.message : "Unable to create project"); setCreating(false); } }
  return <div style={{ background: "#f3f5f8", color: "#172033", fontFamily: "Inter,system-ui,sans-serif" }}>
    <main style={{ maxWidth: 1320, margin: "0 auto", padding: "34px 22px 60px" }}>
      <section style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-end", gap: 20, flexWrap: "wrap", marginBottom: 22 }}><div><div style={{ fontSize: 11, letterSpacing: ".16em", fontWeight: 900, color: "#728078" }}>YOUR WORKSPACE</div><h1 style={{ margin: "7px 0", fontSize: 34, letterSpacing: "-.035em" }}>Projects</h1><p style={{ margin: 0, color: "#64748b", fontSize: 14 }}>Select a project to open its Map &amp; Manage editor.</p></div><button type="button" onClick={() => { setError(""); setShowCreate(true); }} style={{ ...btn, background: "#172033", color: "white", borderColor: "#172033", padding: "11px 16px" }}><Plus size={16} /> Create project</button></section>
      {error && <div style={{ marginBottom: 16, padding: "11px 13px", borderRadius: 9, background: "#fff1f2", border: "1px solid #fecdd3", color: "#be123c", fontSize: 13 }}>{error}</div>}
      <section style={{ background: "white", border: "1px solid #e1e7e3", borderRadius: 12, overflow: "hidden", boxShadow: "0 2px 10px rgba(15,23,42,.04)" }}>
        <div style={{ padding: "14px 18px", borderBottom: "1px solid #e7ece9", display: "flex", justifyContent: "space-between", alignItems: "center" }}><div style={{ fontSize: 11, letterSpacing: ".14em", fontWeight: 900, color: "#728078" }}>PROJECTS YOU CAN ACCESS</div>{!loading && <span style={{ fontSize: 12, color: "#94a3b8" }}>{projects.length} {projects.length === 1 ? "project" : "projects"}</span>}</div>
        {loading ? <div style={{ padding: 40, color: "#64748b", textAlign: "center" }}>Loading projects…</div> : projects.length === 0 ? <div style={{ padding: "58px 24px", textAlign: "center" }}><div style={{ width: 48, height: 48, margin: "0 auto 14px", borderRadius: 12, display: "grid", placeItems: "center", background: "#eef2f0" }}><FolderOpen size={21} /></div><h2 style={{ margin: "0 0 7px", fontSize: 20 }}>No projects yet</h2><p style={{ margin: "0 auto 18px", maxWidth: 430, color: "#64748b", fontSize: 14 }}>Create your first project and start building its master plan, sections and plots.</p><button type="button" onClick={() => setShowCreate(true)} style={{ ...btn, background: "#172033", color: "white", borderColor: "#172033" }}><Plus size={15} /> Create project</button></div> : <div>{projects.map((p, i) => <Link key={p.id} href={`/projects/${p.slug}/editor`} style={{ display: "flex", alignItems: "center", justifyContent: "space-between", gap: 18, padding: "18px 20px", borderBottom: i === projects.length - 1 ? 0 : "1px solid #e7ece9", textDecoration: "none", color: "inherit" }}><div style={{ minWidth: 0, display: "flex", alignItems: "center", gap: 14 }}><div style={{ width: 42, height: 42, flex: "0 0 auto", borderRadius: 10, display: "grid", placeItems: "center", background: "#eef2f0" }}><FolderOpen size={18} /></div><div style={{ minWidth: 0 }}><div style={{ display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap" }}><h2 style={{ margin: 0, fontSize: 17 }}>{p.name}</h2><span style={{ padding: "3px 7px", borderRadius: 999, background: p.role === "admin" ? "#eef2ff" : "#f1f5f9", color: p.role === "admin" ? "#4338ca" : "#475569", fontSize: 10, fontWeight: 900 }}>{p.role.toUpperCase()}</span></div><div style={{ marginTop: 4, color: "#64748b", fontSize: 13, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{p.address || "No address provided"}</div></div></div><div style={{ display: "flex", alignItems: "center", gap: 9, color: "#64748b", flex: "0 0 auto" }}><span style={{ fontSize: 12, fontWeight: 750 }}>Open editor</span><ArrowRight size={16} /></div></Link>)}</div>}
      </section>
    </main>
    {showCreate && <div role="dialog" aria-modal="true" aria-labelledby="create-project-title" onMouseDown={e => e.target === e.currentTarget && setShowCreate(false)} style={{ position: "fixed", inset: 0, zIndex: 50, display: "grid", placeItems: "center", padding: 20, background: "rgba(15,23,42,.48)" }}><div style={{ width: "min(100%,600px)", background: "white", borderRadius: 14, border: "1px solid #e2e8f0", boxShadow: "0 24px 70px rgba(0,0,0,.25)", padding: 25 }}><div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 16 }}><div><div style={{ fontSize: 11, letterSpacing: ".14em", fontWeight: 900, color: "#728078" }}>NEW PROJECT</div><h2 id="create-project-title" style={{ margin: "7px 0 5px", fontSize: 24 }}>Create a project</h2><p style={{ margin: 0, color: "#64748b", fontSize: 13 }}>You will become the project admin and can configure everything from the editor and settings.</p></div><button type="button" onClick={() => setShowCreate(false)} style={{ ...btn, padding: 8 }} aria-label="Close"><X size={16} /></button></div><form onSubmit={create} style={{ display: "grid", gap: 11, marginTop: 22 }}><input required placeholder="Project name" value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} style={{ width: "100%", padding: "12px 13px", border: "1px solid #d8e0db", borderRadius: 8 }} /><input required placeholder="Project address" value={form.address} onChange={e => setForm({ ...form, address: e.target.value })} style={{ width: "100%", padding: "12px 13px", border: "1px solid #d8e0db", borderRadius: 8 }} /><input placeholder="Google Maps location link" value={form.googleLocationUrl} onChange={e => setForm({ ...form, googleLocationUrl: e.target.value })} style={{ width: "100%", padding: "12px 13px", border: "1px solid #d8e0db", borderRadius: 8 }} /><textarea placeholder="Short project description" rows={4} value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} style={{ width: "100%", padding: "12px 13px", border: "1px solid #d8e0db", borderRadius: 8, resize: "vertical" }} /><div style={{ display: "flex", justifyContent: "flex-end", gap: 9 }}><button type="button" onClick={() => setShowCreate(false)} style={btn}>Cancel</button><button type="submit" disabled={creating} style={{ ...btn, background: "#172033", color: "white", borderColor: "#172033", opacity: creating ? .65 : 1 }}>{creating ? "Creating…" : "Create project"}</button></div></form></div></div>}
  </div>;
}
