'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';

type Project = { id:string; slug:string; name:string; address:string; role:'admin'|'sales' };

export default function Projects(){
 const [projects,setProjects]=useState<Project[]>([]),[loading,setLoading]=useState(true),[creating,setCreating]=useState(false),[showCreate,setShowCreate]=useState(false),[error,setError]=useState('');
 const [form,setForm]=useState({name:'',address:'',googleLocationUrl:'',description:''});
 async function load(){setLoading(true);try{const r=await fetch('/api/projects',{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error);setProjects(d.projects||[]);}catch(e){setError(e instanceof Error?e.message:'Unable to load projects');}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 async function create(e:React.FormEvent){e.preventDefault();setCreating(true);setError('');try{const r=await fetch('/api/projects',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const d=await r.json();if(!r.ok)throw new Error(d.error);window.location.href=`/projects/${d.project.slug}`;}catch(e){setError(e instanceof Error?e.message:'Unable to create project');setCreating(false)}}
 async function signOut(){await fetch('/api/auth/signout',{method:'POST',credentials:'same-origin'});window.location.href='/'}
 return <main className="shell"><header className="header"><Link href="/" className="brand"><span>LG</span><b>LANDGRID</b></Link><button type="button" className="header-link" onClick={signOut}>Sign out</button></header>
 <section className="page-heading"><div className="eyebrow">YOUR WORKSPACE</div><div style={{display:'flex',justifyContent:'space-between',alignItems:'flex-end',gap:18,flexWrap:'wrap'}}><div><h1>Projects</h1><p>Open a project you have access to, or create a new project.</p></div><button type="button" className="button primary" onClick={()=>{setError('');setShowCreate(true)}}>+ Create project</button></div></section>
 {error&&<div className="notice">{error}</div>}
 <div className="eyebrow">PROJECTS YOU CAN ACCESS</div>{loading?<div className="project-card"><p>Loading projects…</p></div>:projects.length===0?<div className="project-card"><h2>No projects yet</h2><p>Create your first project using the button above. You will automatically become its admin.</p><button className="button primary" type="button" onClick={()=>setShowCreate(true)}>Create your first project</button></div>:<div style={{display:'grid',gap:14,marginTop:12}}>{projects.map(p=><article className="project-card" key={p.id}><div><div className="eyebrow">{p.role.toUpperCase()}</div><h2>{p.name}</h2><p>{p.address}</p></div><div className="actions"><Link className="button secondary" href={`/projects/${p.slug}`}>View project</Link>{p.role==='admin'&&<Link className="button primary" href={`/projects/${p.slug}/manage`}>Map &amp; Manage</Link>}</div></article>)}</div>}
 {showCreate&&<div role="dialog" aria-modal="true" aria-labelledby="create-project-title" onMouseDown={(e)=>e.target===e.currentTarget&&setShowCreate(false)} style={{position:'fixed',inset:0,zIndex:50,display:'grid',placeItems:'center',padding:20,background:'rgba(15,23,42,.48)'}}><div className="panel" style={{width:'min(100%,620px)',padding:28,boxShadow:'0 24px 70px rgba(0,0,0,.25)'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'flex-start',gap:16}}><div><div className="eyebrow">NEW PROJECT</div><h2 id="create-project-title">Create a project</h2><p>Add the basic project information. You can upload the master plan and drone assets from Settings.</p></div><button type="button" className="button secondary" onClick={()=>setShowCreate(false)}>Close</button></div><form onSubmit={create} style={{display:'grid',gap:12,marginTop:20}}><input className="input" required placeholder="Project name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input className="input" required placeholder="Project address" value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/><input className="input" placeholder="Google Maps location link" value={form.googleLocationUrl} onChange={e=>setForm({...form,googleLocationUrl:e.target.value})}/><textarea className="input" placeholder="Short project description" rows={4} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><div style={{display:'flex',justifyContent:'flex-end',gap:10}}><button type="button" className="button secondary" onClick={()=>setShowCreate(false)}>Cancel</button><button className="button primary" disabled={creating}>{creating?'Creating…':'Create project'}</button></div></form></div></div>}
 </main>
}
