"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { Download, Eye, EyeOff, FolderOpen, Minus, MousePointer2, Move, Plus, Save, Trash2, Upload, X } from "lucide-react";
import styles from "./lot-editor.module.css";

type Lot={id:string;number:string;status:string;area:number|string|null;price:number|string|null;model:string;owner:string;direction:string;points:string;labelX:number;labelY:number;sectionId?:string|null};
type Plan={id:string;name:string;sortOrder:number;masterPlanUrl?:string|null;droneUrl?:string|null};
type Point={x:number;y:number};
const W=1600,H=1000;
const parse=(s:string):Point[]=>s.trim().split(/\s+/).map(v=>v.split(",").map(Number)).filter(v=>Number.isFinite(v[0])&&Number.isFinite(v[1])).map(([x,y])=>({x,y}));
const pointString=(p:Point[])=>p.map(v=>`${Math.round(v.x)},${Math.round(v.y)}`).join(" ");
const center=(p:Point[])=>p.reduce((a,v)=>({x:a.x+v.x/p.length,y:a.y+v.y/p.length}),{x:0,y:0});

export default function LotEditor({projectSlug}:{projectSlug:string}){
 const [plans,setPlans]=useState<Plan[]>([]),[lots,setLots]=useState<Lot[]>([]),[planId,setPlanId]=useState("master_plan"),[selected,setSelected]=useState<string|null>(null),[view,setView]=useState<"map"|"drone">("map"),[zoom,setZoom]=useState(1),[showImage,setShowImage]=useState(true),[tool,setTool]=useState<"select"|"pan">("select"),[dirty,setDirty]=useState(false),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[confirm,setConfirm]=useState<{kind:"lot"|"section";id:string;label:string}|null>(null),[drag,setDrag]=useState<{id:string;start:Point;points:Point[]}|null>(null);
 const fileRef=useRef<HTMLInputElement>(null),jsonRef=useRef<HTMLInputElement>(null);
 const plan=plans.find(p=>p.id===planId)||plans[0];
 const visible=useMemo(()=>lots.filter(l=>(l.sectionId||"master_plan")===plan?.id),[lots,plan]);
 const selectedLot=lots.find(l=>l.id===selected)||null;
 const viewW=W/zoom,viewH=H/zoom,viewBox=`${(W-viewW)/2} ${(H-viewH)/2} ${viewW} ${viewH}`;
 const asset=plan&&(view==="map"?plan.masterPlanUrl:plan.droneUrl);
 const assetUrl=asset?`/api/projects/${encodeURIComponent(projectSlug)}/assets/file?kind=${view==="map"?"master-plan":"drone"}&planType=${encodeURIComponent(plan.id)}&v=${encodeURIComponent(asset)}`:null;
 async function load(){try{const r=await fetch(`/api/projects/${encodeURIComponent(projectSlug)}/plan`,{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to load plan");setPlans(d.sections||[]);setLots(d.lots||[]);setPlanId((p:string)=>(d.sections||[]).some((x:Plan)=>x.id===p)?p:d.sections?.[0]?.id||"master_plan");}catch(e){setMessage(e instanceof Error?e.message:"Unable to load plan");}}
 useEffect(()=>{void load()},[projectSlug]);
 async function save(){if(busy)return;setBusy(true);try{const r=await fetch(`/api/projects/${encodeURIComponent(projectSlug)}/plan`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({sections:plans,lots})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to save");setDirty(false);setMessage("Saved");}catch(e){setMessage(e instanceof Error?e.message:"Unable to save")}finally{setBusy(false)}}
 async function addSection(){if(busy)return;const n=Math.max(0,...plans.map(p=>Number(p.id.match(/^section_(\d+)$/)?.[1]||0)))+1,id=`section_${n}`;setBusy(true);try{const r=await fetch(`/api/projects/${encodeURIComponent(projectSlug)}/plans`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({planType:id})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to add section");setPlans(v=>[...v,{id,name:`Section ${n}`,sortOrder:n,masterPlanUrl:null,droneUrl:null}]);setPlanId(id);setSelected(null);setZoom(1);setMessage(`Section ${n} added`)}catch(e){setMessage(e instanceof Error?e.message:"Unable to add section")}finally{setBusy(false)}}
 async function deleteSection(id:string){setBusy(true);try{const r=await fetch(`/api/projects/${encodeURIComponent(projectSlug)}/plans`,{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({planType:id})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to delete section");setPlans(v=>v.filter(p=>p.id!==id));setLots(v=>v.filter(l=>(l.sectionId||"master_plan")!==id));if(planId===id){setPlanId("master_plan");setSelected(null)}setDirty(false);setMessage(`${confirm?.label||"Section"} deleted`)}catch(e){setMessage(e instanceof Error?e.message:"Unable to delete section")}finally{setBusy(false);setConfirm(null)}}
 function addLot(){if(!plan||busy)return;const nums=visible.map(l=>Number(l.number)).filter(Number.isFinite);const n=String((nums.length?Math.max(...nums):0)+1);const x=W/2-90,y=H/2-50,p=[{x,y},{x:x+180,y},{x:x+180,y:y+100},{x,y:y+100}],c=center(p);const lot:Lot={id:crypto.randomUUID(),number:n,status:"available",area:null,price:null,model:"",owner:"",direction:"",points:pointString(p),labelX:c.x,labelY:c.y,sectionId:plan.id};setLots(v=>[...v,lot]);setSelected(lot.id);setDirty(true);setMessage(`Lot ${n} added — drag it to position`)}
 function updateSelected(field:keyof Lot,value:string){if(!selected)return;setLots(v=>v.map(l=>l.id===selected?{...l,[field]:value}:l));setDirty(true)}
 function canvasPoint(e:React.PointerEvent<SVGSVGElement>):Point{const svg=((e.currentTarget as unknown as SVGGElement).ownerSVGElement||(e.currentTarget as unknown as SVGSVGElement)) as SVGSVGElement,r=svg.getBoundingClientRect(),vb=svg.viewBox.baseVal;return{x:vb.x+((e.clientX-r.left)/r.width)*vb.width,y:vb.y+((e.clientY-r.top)/r.height)*vb.height}}
 function beginDrag(e:React.PointerEvent<SVGGElement>,lot:Lot){if(tool!=="select")return;e.stopPropagation();setSelected(lot.id);setDrag({id:lot.id,start:canvasPoint(e as unknown as React.PointerEvent<SVGSVGElement>),points:parse(lot.points)});(e.currentTarget as SVGGElement).setPointerCapture(e.pointerId)}
 function moveDrag(e:React.PointerEvent<SVGGElement>){if(!drag)return;const p=canvasPoint(e as unknown as React.PointerEvent<SVGSVGElement>),dx=p.x-drag.start.x,dy=p.y-drag.start.y,np=drag.points.map(v=>({x:v.x+dx,y:v.y+dy})),c=center(np);setLots(v=>v.map(l=>l.id===drag.id?{...l,points:pointString(np),labelX:c.x,labelY:c.y}:l));setDirty(true)}
 function endDrag(){setDrag(null)}
 function importLots(file:File){const r=new FileReader();r.onload=()=>{try{const rows=JSON.parse(String(r.result));if(!Array.isArray(rows))throw new Error();const imported=rows.map((x:any,i:number)=>({id:String(x.id||crypto.randomUUID()),number:String(x.number||i+1),status:String(x.status||"available"),area:x.area??null,price:x.price??null,model:String(x.model||""),owner:String(x.owner||""),direction:String(x.direction||""),points:String(x.points||""),labelX:Number(x.labelX||0),labelY:Number(x.labelY||0),sectionId:planId}));setLots(v=>[...v.filter(l=>(l.sectionId||"master_plan")!==planId),...imported]);setDirty(true);setMessage(`${imported.length} lots imported`)}catch{setMessage("Invalid lots.json")}};r.readAsText(file)}
 function exportLots(){const a=document.createElement("a"),url=URL.createObjectURL(new Blob([JSON.stringify(visible,null,2)],{type:"application/json"}));a.href=url;a.download=`${plan?.id||"master_plan"}-lots.json`;a.click();URL.revokeObjectURL(url)}
 async function upload(file:File){if(!plan)return;try{const f=new FormData();f.append("file",file);f.append("planType",plan.id);f.append("kind",view==="map"?"master-plan":"drone");const r=await fetch(`/api/projects/${encodeURIComponent(projectSlug)}/assets`,{method:"POST",body:f});const d=await r.json();if(!r.ok)throw new Error(d.error||"Upload failed");setPlans(v=>v.map(p=>p.id===plan.id?{...p,...(view==="map"?{masterPlanUrl:d.savedValue}:{droneUrl:d.savedValue})}:p));setMessage(`${view} uploaded`)}catch(e){setMessage(e instanceof Error?e.message:"Upload failed")}}
 function selectPlan(id:string){setPlanId(id);setSelected(null);setZoom(1);setView("map")}
 return <div className={styles.editor}>
  <header className={styles.header}><div><div className={styles.eyebrow}>LANDGRID / MAP AND MANAGE</div><h1>Lot Editor</h1><span>{plan?.name||"Master Plan"}</span></div><div className={styles.actions}><button type="button" onClick={()=>jsonRef.current?.click()}><FolderOpen size={16}/> Import lots</button><button type="button" onClick={exportLots}><Download size={16}/> Export lots</button><button type="button" className={styles.primary} disabled={busy} onClick={save}><Save size={16}/> {busy?"Working…":"Save"}{dirty?" *":""}</button></div></header>
  <main className={styles.body}><aside className={styles.sidebar}><div className={styles.sideTop}><div><b>Map & Manage</b><small>{plan?.name||"Master Plan"}</small></div></div><div style={{padding:12,display:"grid",gap:8}}><button type="button" className={styles.primary} disabled={busy} onClick={addSection}><Plus size={16}/> Add section</button><button type="button" className={styles.primary} disabled={busy||!plan} onClick={addLot}><Plus size={16}/> Add lot</button></div><div style={{padding:"8px 12px",fontSize:12,fontWeight:700,opacity:.65}}>PLANS</div><div className={styles.lotList}>{plans.map(p=><div key={p.id} style={{display:"flex",gap:4}}><button type="button" style={{flex:1,textAlign:"left"}} className={`${styles.lotCard} ${plan?.id===p.id?styles.selected:""}`} onClick={()=>selectPlan(p.id)}><span className={styles.lotNumber}>{p.id==="master_plan"?"M":p.id.replace("section_","S")}</span><span><b>{p.name}</b><small>{lots.filter(l=>(l.sectionId||"master_plan")===p.id).length} lots</small></span></button>{p.id!=="master_plan"&&<button type="button" disabled={busy} title="Delete section" onClick={()=>setConfirm({kind:"section",id:p.id,label:p.name})} style={{width:42}}><Trash2 size={15}/></button>}</div>)}</div><div style={{padding:"12px 12px 8px",fontSize:12,fontWeight:700,opacity:.65}}>LOTS</div><div className={styles.lotList}>{visible.map(l=><button type="button" key={l.id} className={`${styles.lotCard} ${selected===l.id?styles.selected:""}`} onClick={()=>setSelected(l.id)}><span className={styles.lotNumber}>{l.number}</span><span><b>Lot {l.number}</b><small>{l.status}{l.owner?` · ${l.owner}`:""}</small></span></button>)}{!visible.length&&<div className={styles.empty}>No lots yet.</div>}</div></aside>
  <section className={styles.stage}><div className={styles.toolbar}><button type="button" className={tool==="select"?styles.active:""} onClick={()=>setTool("select")}><MousePointer2 size={17}/></button><button type="button" className={tool==="pan"?styles.active:""} onClick={()=>setTool("pan")}><Move size={17}/></button><span className={styles.separator}/><button type="button" onClick={()=>setZoom(z=>Math.min(8,Number((z+.25).toFixed(2))))}><Plus size={17}/></button><strong>{Math.round(zoom*100)}%</strong><button type="button" onClick={()=>setZoom(z=>Math.max(.25,Number((z-.25).toFixed(2))))}><Minus size={17}/></button><input aria-label="Map zoom" type="range" min="0.25" max="8" step="0.05" value={zoom} onChange={e=>setZoom(Number(e.target.value))} style={{width:130}}/><button type="button" onClick={()=>setZoom(1)}>Fit</button><span className={styles.separator}/><button type="button" className={view==="map"?styles.active:""} onClick={()=>setView("map")}>Map</button><button type="button" className={view==="drone"?styles.active:""} onClick={()=>setView("drone")}>Drone</button><button type="button" onClick={()=>fileRef.current?.click()}><Upload size={16}/> Upload</button><button type="button" onClick={()=>setShowImage(v=>!v)}>{showImage?<EyeOff size={16}/>:<Eye size={16}/>} {showImage?"Hide image":"Show image"}</button><span className={styles.spacer}/><span className={styles.hint}>{message||"Add a lot, then drag it into position"}</span></div><input ref={fileRef} hidden type="file" accept=".svg,.png,.jpg,.jpeg,.webp" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])}/><input ref={jsonRef} hidden type="file" accept=".json,application/json" onChange={e=>e.target.files?.[0]&&importLots(e.target.files[0])}/><div className={styles.canvasWrap}><div className={styles.canvas}><svg viewBox={viewBox} preserveAspectRatio="none" style={{position:"absolute",inset:0,width:"100%",height:"100%",touchAction:"none"}}>{assetUrl&&showImage&&<image href={assetUrl} x="0" y="0" width={W} height={H} preserveAspectRatio="none" pointerEvents="none"/>}{visible.map(l=><g key={l.id} onPointerDown={e=>beginDrag(e,l)} onPointerMove={moveDrag} onPointerUp={endDrag} onPointerCancel={endDrag} style={{cursor:selected===l.id?"move":"pointer"}}><polygon points={l.points} fill={selected===l.id?"rgba(37,99,235,.35)":"rgba(37,99,235,.10)"} stroke={selected===l.id?"#2457d6":"#fff"} strokeWidth={selected===l.id?4:2}/><text x={l.labelX} y={l.labelY} textAnchor="middle" dominantBaseline="middle" fontSize="24" fontWeight="800" fill="#172033" paintOrder="stroke" stroke="#fff" strokeWidth="5" pointerEvents="none">{l.number}</text></g>)}</svg>{!assetUrl&&<div className={styles.empty}>Upload a {view} for this plan.</div>}</div></div></section>
  {selectedLot&&<aside className={styles.sidebar}><div className={styles.sideTop}><div><b>Lot {selectedLot.number}</b><small>Edit lot details</small></div><button type="button" onClick={()=>setSelected(null)}><X size={16}/></button></div><div style={{padding:16,display:"grid",gap:12}}><label>Lot number<input value={selectedLot.number} onChange={e=>updateSelected("number",e.target.value)}/></label><label>Status<select value={selectedLot.status} onChange={e=>updateSelected("status",e.target.value)}><option value="available">Available</option><option value="reserved">Reserved</option><option value="sold">Sold</option><option value="hold">Hold</option></select></label><label>Owner<input value={selectedLot.owner} onChange={e=>updateSelected("owner",e.target.value)}/></label><label>Price<input type="number" value={selectedLot.price??""} onChange={e=>updateSelected("price",e.target.value)}/></label><label>Area<input type="number" value={selectedLot.area??""} onChange={e=>updateSelected("area",e.target.value)}/></label><label>Model<input value={selectedLot.model} onChange={e=>updateSelected("model",e.target.value)}/></label><label>Direction<input value={selectedLot.direction} onChange={e=>updateSelected("direction",e.target.value)}/></label><button type="button" disabled={busy} onClick={()=>setConfirm({kind:"lot",id:selectedLot.id,label:`Lot ${selectedLot.number}`})}><Trash2 size={16}/> Delete lot</button></div></aside>}
  {confirm&&<div style={{position:"fixed",inset:0,zIndex:1000,background:"rgba(15,23,42,.5)",display:"grid",placeItems:"center",padding:20}}><div style={{background:"white",borderRadius:16,width:"min(440px,100%)",padding:24,boxShadow:"0 20px 60px rgba(0,0,0,.2)"}}><h2 style={{marginTop:0}}>Delete {confirm.label}?</h2><p style={{color:"#64748b",lineHeight:1.5}}>{confirm.kind==="section"?"This will permanently remove the section and all lots in it. Master Plan is protected and cannot be deleted.":"This will remove the lot from this project. You can save the remaining changes afterward."}</p><div style={{display:"flex",justifyContent:"flex-end",gap:10}}><button type="button" onClick={()=>setConfirm(null)}>Cancel</button><button type="button" disabled={busy} onClick={()=>confirm.kind==="section"?void deleteSection(confirm.id):(setLots(v=>v.filter(l=>l.id!==confirm.id)),setSelected(null),setDirty(true),setMessage(`${confirm.label} deleted`),setConfirm(null))} style={{background:"#dc2626",color:"white",border:0,borderRadius:8,padding:"9px 14px"}}>Delete</button></div></div></div>}
 </main></div>;
}
