"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { Download, Eye, EyeOff, FolderOpen, Grid2X2, Minus, MousePointer2, Move, Plus, Save, Upload } from "lucide-react";
import styles from "./lot-editor.module.css";

type Lot = { id:string; number:string; status:string; area:number|string|null; price:number|string|null; model:string; owner:string; direction:string; points:string; labelX:number; labelY:number; sectionId?:string|null };
type Plan = { id:string; name:string; sortOrder:number; masterPlanUrl?:string|null; droneUrl?:string|null };
type Point = {x:number;y:number};

const parse=(s:string):Point[]=>s.trim().split(/\s+/).map(v=>v.split(",").map(Number)).filter(v=>Number.isFinite(v[0])&&Number.isFinite(v[1])).map(([x,y])=>({x,y}));
const points=(p:Point[])=>p.map(v=>`${Math.round(v.x)},${Math.round(v.y)}`).join(" ");
const bounds=(lots:Lot[])=>{const p=lots.flatMap(l=>parse(l.points));if(!p.length)return{minX:0,minY:0,maxX:1600,maxY:1000};return{minX:Math.min(...p.map(v=>v.x)),minY:Math.min(...p.map(v=>v.y)),maxX:Math.max(...p.map(v=>v.x)),maxY:Math.max(...p.map(v=>v.y))};};

export default function LotEditor({projectSlug}:{projectSlug:string}){
 const [plans,setPlans]=useState<Plan[]>([]),[lots,setLots]=useState<Lot[]>([]),[planId,setPlanId]=useState("master_plan"),[selected,setSelected]=useState<string|null>(null),[view,setView]=useState<"map"|"drone">("map"),[zoom,setZoom]=useState(1),[showImage,setShowImage]=useState(true),[tool,setTool]=useState<"select"|"draw"|"pan">("select"),[draft,setDraft]=useState<Point[]>([]),[dirty,setDirty]=useState(false),[message,setMessage]=useState("");
 const fileRef=useRef<HTMLInputElement>(null),jsonRef=useRef<HTMLInputElement>(null);
 const plan=plans.find(p=>p.id===planId)||plans[0];
 const visible=useMemo(()=>lots.filter(l=>(l.sectionId||"master_plan")===plan?.id),[lots,plan]);
 const b=bounds(visible);const viewBox=`${b.minX-100} ${b.minY-100} ${Math.max(1,b.maxX-b.minX+200)} ${Math.max(1,b.maxY-b.minY+200)}`;
 const asset=plan&&(view==="map"?plan.masterPlanUrl:plan.droneUrl);const assetUrl=asset?`/api/projects/${encodeURIComponent(projectSlug)}/assets/file?kind=${view==="map"?"master-plan":"drone"}&planType=${encodeURIComponent(plan.id)}&v=${Date.now()}`:null;
 async function load(){try{const r=await fetch(`/api/projects/${encodeURIComponent(projectSlug)}/plan`,{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to load plan");setPlans(d.sections||[]);setLots(d.lots||[]);setPlanId((p:string)=>(d.sections||[]).some((x:Plan)=>x.id===p)?p:d.sections?.[0]?.id||"master_plan");}catch(e){setMessage(e instanceof Error?e.message:"Unable to load plan");}}
 useEffect(()=>{void load();},[projectSlug]);
 async function save(){try{const r=await fetch(`/api/projects/${encodeURIComponent(projectSlug)}/plan`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({sections:plans,lots})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to save");setDirty(false);setMessage("Saved");void load();}catch(e){setMessage(e instanceof Error?e.message:"Unable to save");}}
 async function addSection(){const n=Math.max(0,...plans.map(p=>Number(p.id.match(/^section_(\d+)$/)?.[1]||0)))+1;const id=`section_${n}`;try{const r=await fetch(`/api/projects/${encodeURIComponent(projectSlug)}/plans`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({planType:id})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to add section");setPlans(v=>[...v,{id,name:`Section ${n}`,sortOrder:n,masterPlanUrl:null,droneUrl:null}]);setPlanId(id);setView("map");setMessage(`Section ${n} added`);}catch(e){setMessage(e instanceof Error?e.message:"Unable to add section");}}
 async function upload(file:File){if(!plan)return;try{const f=new FormData();f.append("file",file);f.append("planType",plan.id);f.append("kind",view==="map"?"master-plan":"drone");const r=await fetch(`/api/projects/${encodeURIComponent(projectSlug)}/assets`,{method:"POST",body:f});const d=await r.json();if(!r.ok)throw new Error(d.error||"Upload failed");setPlans(v=>v.map(p=>p.id===plan.id?{...p,...(view==="map"?{masterPlanUrl:d.savedValue}:{droneUrl:d.savedValue})}:p));setMessage(`${view} uploaded`);}catch(e){setMessage(e instanceof Error?e.message:"Upload failed");}}
 function importLots(file:File){const r=new FileReader();r.onload=()=>{try{const data=JSON.parse(String(r.result));const rows=Array.isArray(data)?data:[];const imported=rows.map((x:any,i:number)=>({id:String(x.id||crypto.randomUUID()),number:String(x.number||i+1),status:String(x.status||"available"),area:x.area??null,price:x.price??null,model:String(x.model||""),owner:String(x.owner||""),direction:String(x.direction||""),points:String(x.points||""),labelX:Number(x.labelX||0),labelY:Number(x.labelY||0),sectionId:planId}));setLots(v=>[...v.filter(l=>(l.sectionId||"master_plan")!==planId),...imported]);setDirty(true);}catch{setMessage("Invalid lots.json");}};r.readAsText(file);}
 function exportLots(){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(lots,null,2)],{type:"application/json"}));a.download="lots.json";a.click();}
 function finishDraw(){if(draft.length<3||!plan)return;const n=String(Math.max(0,...lots.map(l=>Number(l.number)).filter(Number.isFinite))+1);const c=draft.reduce((a,p)=>({x:a.x+p.x/draft.length,y:a.y+p.y/draft.length}),{x:0,y:0});const lot:Lot={id:crypto.randomUUID(),number:n,status:"available",area:null,price:null,model:"",owner:"",direction:"",points:points(draft),labelX:c.x,labelY:c.y,sectionId:plan.id};setLots(v=>[...v,lot]);setSelected(lot.id);setDraft([]);setTool("select");setDirty(true);}
 return <div className={styles.editor}>
  <header className={styles.header}><div><div className={styles.eyebrow}>LANDGRID / MAP AND MANAGE</div><h1>Lot Editor</h1><span>{plan?.name||"Master"}</span></div><div className={styles.actions}><button onClick={()=>jsonRef.current?.click()}><FolderOpen size={16}/> Import lots</button><button onClick={exportLots}><Download size={16}/> Export lots</button><button className={styles.primary} onClick={save}><Save size={16}/> Save{dirty?" *":""}</button></div></header>
  <div className={styles.toolbar}><label>Plan <select value={planId} onChange={e=>setPlanId(e.target.value)}>{plans.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><button onClick={addSection}><Plus size={16}/> Add section</button><span className={styles.separator}/><button className={tool==="select"?styles.active:""} onClick={()=>setTool("select")}><MousePointer2 size={17}/></button><button className={tool==="pan"?styles.active:""} onClick={()=>setTool("pan")}><Move size={17}/></button><button className={tool==="draw"?styles.active:""} onClick={()=>setTool("draw")}><Grid2X2 size={17}/></button>{tool==="draw"&&<button onClick={finishDraw}>Finish lot</button>}<span className={styles.separator}/><button onClick={()=>setZoom(z=>Math.min(8,z+.25))}><Plus size={17}/></button><strong>{Math.round(zoom*100)}%</strong><button onClick={()=>setZoom(z=>Math.max(.25,z-.25))}><Minus size={17}/></button><button onClick={()=>setZoom(1)}>Fit</button><span className={styles.separator}/><button className={view==="map"?styles.active:""} onClick={()=>setView("map")}>Map</button><button className={view==="drone"?styles.active:""} onClick={()=>setView("drone")}>Drone</button><button onClick={()=>fileRef.current?.click()}><Upload size={16}/> Upload {view}</button><button onClick={()=>setShowImage(v=>!v)}>{showImage?<EyeOff size={16}/>:<Eye size={16}/>} {showImage?"Hide image":"Show image"}</button><span className={styles.spacer}/><span className={styles.hint}>{message||"Select a lot to edit"}</span></div>
  <input ref={fileRef} hidden type="file" accept=".svg,.png,.jpg,.jpeg,.webp" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])}/><input ref={jsonRef} hidden type="file" accept=".json,application/json" onChange={e=>e.target.files?.[0]&&importLots(e.target.files[0])}/>
  <main className={styles.body}><aside className={styles.sidebar}><div className={styles.sideTop}><div><b>Lots</b><small>{visible.length} in {plan?.name||"Master"}</small></div></div><div className={styles.lotList}>{visible.map(l=><button key={l.id} className={`${styles.lotCard} ${selected===l.id?styles.selected:""}`} onClick={()=>setSelected(l.id)}><span className={styles.lotNumber}>{l.number}</span><span><b>Lot {l.number}</b><small>{l.status}{l.owner?` · ${l.owner}`:""}</small></span></button>)}</div></aside>
   <section className={styles.stage}><div className={styles.canvasWrap}><div className={styles.canvas}>{assetUrl&&showImage?<img src={assetUrl} alt={plan?.name||"plan"} style={{position:"absolute",inset:0,width:"100%",height:"100%",objectFit:"fill",pointerEvents:"none"}}/>:<div className={styles.empty}>Upload a {view} for this plan.</div>}<svg viewBox={viewBox} preserveAspectRatio="none" style={{position:"absolute",inset:0,width:"100%",height:"100%"}}>{visible.map(l=><g key={l.id} onClick={()=>setSelected(l.id)}><polygon points={l.points} fill={selected===l.id?"rgba(37,99,235,.35)":"rgba(37,99,235,.08)"} stroke={selected===l.id?"#2457d6":"#fff"} strokeWidth={selected===l.id?4:2}/><text x={l.labelX} y={l.labelY} textAnchor="middle" dominantBaseline="middle" fontSize="24" fontWeight="800" fill="#172033" paintOrder="stroke" stroke="#fff" strokeWidth="5">{l.number}</text></g>)}{draft.length>1&&<polyline points={draft.map(p=>`${p.x},${p.y}`).join(" ")} fill="none" stroke="#2457d6" strokeWidth="4"/>}</svg></div></div></section></main>
 </div>;
}