"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { Minus, Plus, Save, Trash2, X } from "lucide-react";

type Plan={id:string;name:string;masterPlanUrl?:string|null;droneUrl?:string|null};
type Plot={id:string;number:string;status:string;owner:string;price:number|string|null;area:number|string|null;direction:string;model:string;points:string;labelX:number;labelY:number;sectionId:string};
type Point={x:number;y:number};
const W=1600,H=1000;
const parse=(s:string):Point[]=>s.trim().split(/\s+/).filter(Boolean).map(v=>v.split(",").map(Number)).filter(v=>Number.isFinite(v[0])&&Number.isFinite(v[1])).map(([x,y])=>({x,y}));
const stringify=(p:Point[])=>p.map(v=>`${Math.round(v.x)},${Math.round(v.y)}`).join(" ");
const center=(p:Point[])=>({x:p.reduce((a,v)=>a+v.x,0)/p.length,y:p.reduce((a,v)=>a+v.y,0)/p.length});

export default function PlotEditor({projectSlug}:{projectSlug:string}){
 const [plans,setPlans]=useState<Plan[]>([]),[plots,setPlots]=useState<Plot[]>([]),[planId,setPlanId]=useState("master_plan"),[selected,setSelected]=useState<string|null>(null),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[confirm,setConfirm]=useState<{kind:"plot"|"section";id:string;label:string}|null>(null),[zoomX,setZoomX]=useState(1),[zoomY,setZoomY]=useState(1),[drag,setDrag]=useState<{id:string;start:Point;points:Point[]}|null>(null);
 const svgRef=useRef<SVGSVGElement>(null);
 const plan=plans.find(p=>p.id===planId)||plans[0];
 const visible=useMemo(()=>plots.filter(p=>p.sectionId===plan?.id),[plots,plan]);
 const selectedPlot=plots.find(p=>p.id===selected)||null;
 const viewW=W/zoomX,viewH=H/zoomY,viewBox=`${(W-viewW)/2} ${(H-viewH)/2} ${viewW} ${viewH}`;
 const asset=plan?.masterPlanUrl;
 const assetUrl=asset?`/api/projects/${encodeURIComponent(projectSlug)}/assets/file?kind=master-plan&planType=${encodeURIComponent(plan.id)}&v=${encodeURIComponent(asset)}`:null;
 async function load(){try{const r=await fetch(`/api/projects/${encodeURIComponent(projectSlug)}/plan`,{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to load plans");setPlans(d.sections||[]);setPlots(d.lots||[]);if((d.sections||[]).length)setPlanId((d.sections||[]).some((p:Plan)=>p.id===planId)?planId:d.sections[0].id);}catch(e){setMessage(e instanceof Error?e.message:"Unable to load plans")}}
 useEffect(()=>{void load()},[projectSlug]);
 async function save(){if(busy)return;setBusy(true);try{const r=await fetch(`/api/projects/${encodeURIComponent(projectSlug)}/plan`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({sections:plans,lots:plots})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to save");setMessage(`Saved${d.deletedPlots?` · ${d.deletedPlots} plot deleted`:""}`);}catch(e){setMessage(e instanceof Error?e.message:"Unable to save")}finally{setBusy(false)}}
 async function addSection(){if(busy)return;const n=Math.max(0,...plans.map(p=>Number(p.id.match(/^section_(\d+)$/)?.[1]||0)))+1,id=`section_${n}`;setBusy(true);try{const r=await fetch(`/api/projects/${encodeURIComponent(projectSlug)}/plans`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({planType:id})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to add section");setPlans(v=>[...v,{id,name:`Section ${n}`,masterPlanUrl:null,droneUrl:null}]);setPlanId(id);setMessage(`Section ${n} added`)}catch(e){setMessage(e instanceof Error?e.message:"Unable to add section")}finally{setBusy(false)}}
 async function deleteSection(id:string){if(id==="master_plan"||busy)return;setBusy(true);try{const r=await fetch(`/api/projects/${encodeURIComponent(projectSlug)}/plans`,{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({planType:id})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to delete project section");setPlans(v=>v.filter(p=>p.id!==id));setPlots(v=>v.filter(p=>p.sectionId!==id));if(planId===id)setPlanId("master_plan");setSelected(null);setMessage("Section deleted")}catch(e){setMessage(e instanceof Error?e.message:"Unable to delete project section")}finally{setBusy(false);setConfirm(null)}}
 function addPlot(){if(!plan||busy)return;const n=String(Math.max(0,...visible.map(p=>Number(p.number)).filter(Number.isFinite))+1);const x=W/2-90,y=H/2-50,points=[{x,y},{x:x+180,y},{x:x+180,y:y+100},{x,y:y+100}],c=center(points);const p:Plot={id:crypto.randomUUID(),number:n,status:"available",owner:"",price:null,area:null,direction:"",model:"",points:stringify(points),labelX:c.x,labelY:c.y,sectionId:plan.id};setPlots(v=>[...v,p]);setSelected(p.id);setMessage(`Plot ${n} added — drag to position`)}
 function canvasPoint(e:React.PointerEvent):Point{const svg=svgRef.current;if(!svg)return{x:0,y:0};const r=svg.getBoundingClientRect(),vb=svg.viewBox.baseVal;return{x:vb.x+(e.clientX-r.left)/r.width*vb.width,y:vb.y+(e.clientY-r.top)/r.height*vb.height}}
 function startDrag(e:React.PointerEvent,plot:Plot){e.stopPropagation();setSelected(plot.id);setDrag({id:plot.id,start:canvasPoint(e),points:parse(plot.points)});(e.currentTarget as SVGGraphicsElement).setPointerCapture(e.pointerId)}
 function moveDrag(e:React.PointerEvent){if(!drag)return;const p=canvasPoint(e),dx=p.x-drag.start.x,dy=p.y-drag.start.y,np=drag.points.map(v=>({x:v.x+dx,y:v.y+dy})),c=center(np);setPlots(v=>v.map(x=>x.id===drag.id?{...x,points:stringify(np),labelX:c.x,labelY:c.y}:x))}
 function endDrag(){setDrag(null)}
 function update(field:keyof Plot,value:string){if(!selected)return;setPlots(v=>v.map(p=>p.id===selected?{...p,[field]:value}:p))}
 function confirmDelete(){if(!confirm)return;if(confirm.kind==="section")void deleteSection(confirm.id);else{setPlots(v=>v.filter(p=>p.id!==confirm.id));if(selected===confirm.id)setSelected(null);setMessage("Plot deleted");setConfirm(null)}}
 return <div style={{height:"100vh",display:"grid",gridTemplateRows:"72px 1fr",fontFamily:"Inter,system-ui,sans-serif",background:"#f6f7f9",color:"#172033"}}>
  <header style={{display:"flex",alignItems:"center",justifyContent:"space-between",padding:"0 20px",background:"white",borderBottom:"1px solid #e5e7eb"}}><div><small style={{color:"#64748b",fontWeight:700}}>LANDGRID / MAP & MANAGE</small><h2 style={{margin:2}}>Plot Editor <span style={{fontSize:14,fontWeight:500,color:"#64748b"}}>· {plan?.name||"Master Plan"}</span></h2></div><button type="button" onClick={save} disabled={busy} style={{border:0,borderRadius:8,padding:"10px 16px",background:"#172033",color:"white",fontWeight:700}}><Save size={16} style={{verticalAlign:"middle",marginRight:6}}/>{busy?"Saving…":"Save"}</button></header>
  <div style={{display:"grid",gridTemplateColumns:"260px 1fr 260px",minHeight:0}}>
   <aside style={{background:"white",borderRight:"1px solid #e5e7eb",overflow:"auto",padding:12}}><button type="button" onClick={addSection} disabled={busy} style={{width:"100%",padding:10,marginBottom:8}}>+ Add section</button><button type="button" onClick={addPlot} disabled={busy||!plan} style={{width:"100%",padding:10,marginBottom:16}}>+ Add plot</button><b style={{fontSize:12,color:"#64748b"}}>PLANS</b>{plans.map(p=><div key={p.id} style={{display:"flex",gap:4,marginTop:6}}><button type="button" onClick={()=>{setPlanId(p.id);setSelected(null);setZoomX(1);setZoomY(1)}} style={{flex:1,textAlign:"left",padding:9,border:"1px solid #e5e7eb",background:p.id===plan?.id?"#eef2ff":"white",borderRadius:7}}>{p.name}</button>{p.id!=="master_plan"&&<button type="button" title="Delete section" onClick={()=>setConfirm({kind:"section",id:p.id,label:p.name})}><Trash2 size={15}/></button>}</div>)}<b style={{display:"block",fontSize:12,color:"#64748b",marginTop:18}}>PLOTS</b>{visible.map(p=><button type="button" key={p.id} onClick={()=>setSelected(p.id)} style={{display:"block",width:"100%",textAlign:"left",marginTop:5,padding:8,border:"1px solid #e5e7eb",background:selected===p.id?"#dbeafe":"white",borderRadius:7}}>Plot {p.number}<small style={{display:"block",color:"#64748b"}}>{p.status}</small></button>)}</aside>
   <main style={{position:"relative",minWidth:0,background:"#e5e7eb"}}><div style={{position:"absolute",zIndex:5,top:12,left:12,right:12,display:"flex",alignItems:"center",gap:8,background:"rgba(255,255,255,.94)",padding:8,borderRadius:10,boxShadow:"0 2px 12px rgba(0,0,0,.08)"}}><b>Zoom</b><span>H</span><button type="button" onClick={()=>setZoomX(v=>Math.max(.25,+(v-.1).toFixed(2)))}><Minus size={14}/></button><input aria-label="Horizontal zoom" type="range" min=".25" max="8" step=".05" value={zoomX} onChange={e=>setZoomX(+e.target.value)} style={{width:130}}/><button type="button" onClick={()=>setZoomX(v=>Math.min(8,+(v+.1).toFixed(2)))}><Plus size={14}/></button><span>{Math.round(zoomX*100)}%</span><span>V</span><button type="button" onClick={()=>setZoomY(v=>Math.max(.25,+(v-.1).toFixed(2)))}><Minus size={14}/></button><input aria-label="Vertical zoom" type="range" min=".25" max="8" step=".05" value={zoomY} onChange={e=>setZoomY(+e.target.value)} style={{width:130}}/><button type="button" onClick={()=>setZoomY(v=>Math.min(8,+(v+.1).toFixed(2)))}><Plus size={14}/></button><span>{Math.round(zoomY*100)}%</span><button type="button" onClick={()=>{setZoomX(1);setZoomY(1)}}>Fit</button><span style={{marginLeft:"auto",color:"#64748b",fontSize:12}}>{message}</span></div><svg ref={svgRef} viewBox={viewBox} preserveAspectRatio="none" style={{position:"absolute",inset:0,width:"100%",height:"100%",touchAction:"none",background:"#dfe3e8"}}>{assetUrl&&<image href={assetUrl} x="0" y="0" width={W} height={H} preserveAspectRatio="none" pointerEvents="none"/>}{visible.map(p=><g key={p.id} onPointerDown={e=>startDrag(e,p)} onPointerMove={moveDrag} onPointerUp={endDrag} onPointerCancel={endDrag} style={{cursor:"move"}}><polygon points={p.points} fill={selected===p.id?"rgba(37,99,235,.32)":"rgba(37,99,235,.12)"} stroke={selected===p.id?"#1d4ed8":"#334155"} strokeWidth={selected===p.id?4:2}/><text x={p.labelX} y={p.labelY} textAnchor="middle" dominantBaseline="middle" fontSize="24" fontWeight="800" fill="#172033" paintOrder="stroke" stroke="white" strokeWidth="5" pointerEvents="none">{p.number}</text></g>)}</svg>{!assetUrl&&<div style={{position:"absolute",inset:0,display:"grid",placeItems:"center",color:"#64748b"}}>Upload a master plan to position plots.</div>}</main>
   <aside style={{background:"white",borderLeft:"1px solid #e5e7eb",padding:16,overflow:"auto"}}>{selectedPlot?<><div style={{display:"flex",justifyContent:"space-between"}}><div><b>Plot {selectedPlot.number}</b><small style={{display:"block",color:"#64748b"}}>Edit plot</small></div><button type="button" onClick={()=>setSelected(null)}><X size={16}/></button></div><label style={{display:"block",marginTop:16}}>Plot number<input value={selectedPlot.number} onChange={e=>update("number",e.target.value)} style={{width:"100%"}}/></label><label style={{display:"block",marginTop:10}}>Status<select value={selectedPlot.status} onChange={e=>update("status",e.target.value)} style={{width:"100%"}}><option>available</option><option>reserved</option><option>sold</option><option>hold</option></select></label><label style={{display:"block",marginTop:10}}>Owner<input value={selectedPlot.owner} onChange={e=>update("owner",e.target.value)} style={{width:"100%"}}/></label><label style={{display:"block",marginTop:10}}>Price<input value={selectedPlot.price??""} onChange={e=>update("price",e.target.value)} style={{width:"100%"}}/></label><button type="button" onClick={()=>setConfirm({kind:"plot",id:selectedPlot.id,label:`Plot ${selectedPlot.number}`})} style={{marginTop:18,width:"100%",padding:10,color:"#b91c1c"}}><Trash2 size={15}/> Delete plot</button></>:<div style={{color:"#64748b"}}>Select a plot to edit.</div>}</aside>
  </div>
  {confirm&&<div style={{position:"fixed",inset:0,zIndex:50,display:"grid",placeItems:"center",background:"rgba(15,23,42,.45)"}}><div style={{width:380,background:"white",borderRadius:12,padding:22,boxShadow:"0 20px 50px rgba(0,0,0,.2)"}}><h3 style={{marginTop:0}}>Delete {confirm.kind}?</h3><p style={{color:"#64748b"}}>Are you sure you want to delete <b>{confirm.label}</b>? This cannot be undone.</p><div style={{display:"flex",justifyContent:"flex-end",gap:8}}><button type="button" onClick={()=>setConfirm(null)}>Cancel</button><button type="button" onClick={confirmDelete} disabled={busy} style={{background:"#b91c1c",color:"white",border:0,padding:"9px 14px",borderRadius:7}}>Delete</button></div></div></div>}
 </div>;
}
