"use client";
import { useEffect, useRef, useState } from "react";
import { Copy, Save, Trash2, Upload } from "lucide-react";

type Point={x:number;y:number};
type Plan={id:string;name:string;masterPlanUrl?:string|null;droneUrl?:string|null};
type Plot={id:string;number:string;status:string;owner:string;price:unknown;area:unknown;direction:string;model:string;points:string;labelX:number;labelY:number;sectionId?:string|null};
type Drag={kind:"plot-move"|"plot-point"|"section-move"|"section-point";id:string;points:Point[];start:Point;index?:number};
const W=1600,H=1000;
const parse=(s:string):Point[]=>s.trim().split(/\s+/).filter(Boolean).map(v=>v.split(",").map(Number)).filter(v=>Number.isFinite(v[0])&&Number.isFinite(v[1])).map(([x,y])=>({x,y}));
const stringify=(p:Point[])=>p.map(v=>`${Math.round(v.x)},${Math.round(v.y)}`).join(" ");
const center=(p:Point[])=>p.length?{x:p.reduce((a,v)=>a+v.x,0)/p.length,y:p.reduce((a,v)=>a+v.y,0)/p.length}:{x:0,y:0};

export default function PlotEditorV2({projectSlug}:{projectSlug:string}){
 const [plans,setPlans]=useState<Plan[]>([]),[plots,setPlots]=useState<Plot[]>([]),[geo,setGeo]=useState<Record<string,string>>({}),[selectedPlot,setSelectedPlot]=useState<string|null>(null),[selectedSection,setSelectedSection]=useState<string|null>(null),[drag,setDrag]=useState<Drag|null>(null),[dirty,setDirty]=useState(false),[saving,setSaving]=useState(false),[message,setMessage]=useState("");
 const [confirm,setConfirm]=useState<{kind:"plot"|"section";id:string;label:string}|null>(null);
 const [opacity,setOpacity]=useState({plots:1,sections:.5,map:.7,drone:.4});
 const [mapZoom,setMapZoom]=useState({x:1,y:1}),[droneZoom,setDroneZoom]=useState({x:1,y:1});
 const [uploading,setUploading]=useState<"map"|"drone"|null>(null);
 const svgRef=useRef<SVGSVGElement|null>(null),fileRef=useRef<HTMLInputElement|null>(null),uploadKind=useRef<"map"|"drone">("map"),loaded=useRef(false),timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const sections=plans.filter(p=>p.id!=="master_plan"),plot=plots.find(p=>p.id===selectedPlot)??null;
 const asset=(kind:"map"|"drone")=>{const p=plans.find(x=>x.id==="master_plan"),u=kind==="map"?p?.masterPlanUrl:p?.droneUrl;return u?`/api/projects/${encodeURIComponent(projectSlug)}/assets/file?kind=${kind==="map"?"master-plan":"drone"}&planType=master_plan&v=${encodeURIComponent(u)}`:null;};
 const toPoint=(e:React.PointerEvent<SVGElement>)=>{const svg=svgRef.current;if(!svg)return{x:0,y:0};const r=svg.getBoundingClientRect(),v=svg.viewBox.baseVal;return{x:v.x+(e.clientX-r.left)/r.width*v.width,y:v.y+(e.clientY-r.top)/r.height*v.height};};
 const handles=(p:Point[])=>{if(!p.length)return[];const xs=p.map(v=>v.x),ys=p.map(v=>v.y),l=Math.min(...xs),r=Math.max(...xs),t=Math.min(...ys),b=Math.max(...ys);return[{x:l,y:t},{x:(l+r)/2,y:t},{x:r,y:t},{x:r,y:(t+b)/2},{x:r,y:b},{x:(l+r)/2,y:b},{x:l,y:b},{x:l,y:(t+b)/2}];};
 async function load(){const r=await fetch(`/api/projects/${encodeURIComponent(projectSlug)}/plan`,{cache:"no-store"}),d=await r.json();if(!r.ok)throw Error(d.error||"Unable to load");setPlans(d.sections||[]);setPlots(d.lots||[]);try{setGeo(JSON.parse(localStorage.getItem(`landgrid-section-geo:${projectSlug}`)||"{}"));}catch{}loaded.current=true;}
 useEffect(()=>{void load().catch(e=>setMessage(e instanceof Error?e.message:"Unable to load"));},[projectSlug]);
 useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current);},[]);
 useEffect(()=>{if(loaded.current&&dirty){if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>void save(),650);}},[plots,plans,dirty]);
 useEffect(()=>{localStorage.setItem(`landgrid-section-geo:${projectSlug}`,JSON.stringify(geo));},[geo,projectSlug]);
 async function save(){if(!loaded.current||saving||!dirty)return;setSaving(true);try{const r=await fetch(`/api/projects/${encodeURIComponent(projectSlug)}/plan`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({sections:plans,lots:plots})}),d=await r.json();if(!r.ok)throw Error(d.error||"Unable to save");setDirty(false);setMessage("Saved");}catch(e){setMessage(e instanceof Error?e.message:"Unable to save");}finally{setSaving(false);}}
 async function addSection(){const n=Math.max(0,...sections.map(s=>Number(s.id.replace("section_",""))).filter(Number.isFinite))+1,id=`section_${n}`,r=await fetch(`/api/projects/${encodeURIComponent(projectSlug)}/plans`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({planType:id})}),d=await r.json();if(!r.ok){setMessage(d.error||"Unable to add section");return;}setPlans(v=>[...v,{id,name:`Section ${n}`}]);const x=150+((n-1)%3)*480,y=120+Math.floor((n-1)/3)*300;setGeo(v=>({...v,[id]:stringify([{x,y},{x:x+360,y},{x:x+360,y:y+230},{x,y:y+230}])}));setSelectedSection(id);setSelectedPlot(null);setDirty(true);}
 async function deleteSection(id:string){if(id==="master_plan")return;const r=await fetch(`/api/projects/${encodeURIComponent(projectSlug)}/plans`,{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({planType:id})}),d=await r.json();if(!r.ok){setMessage(d.error||"Unable to delete section");return;}setPlans(v=>v.filter(p=>p.id!==id));setGeo(v=>{const n={...v};delete n[id];return n});setSelectedSection(null);setConfirm(null);setDirty(true);setMessage("Section deleted; plots preserved");}
 function addPlot(){const n=String(Math.max(0,...plots.map(p=>Number(p.number)).filter(Number.isFinite))+1),x=620,y=420,q=[{x,y},{x:x+180,y},{x:x+180,y:y+110},{x,y:y+110}],c=center(q),p:Plot={id:crypto.randomUUID(),number:n,status:"available",owner:"",price:null,area:null,direction:"",model:"",points:stringify(q),labelX:c.x,labelY:c.y,sectionId:null};setPlots(v=>[...v,p]);setSelectedPlot(p.id);setSelectedSection(null);setDirty(true);}
 function duplicatePlot(){if(!plot)return;const q=parse(plot.points).map(p=>({x:p.x+40,y:p.y+40})),c=center(q),n=String(Math.max(0,...plots.map(p=>Number(p.number)).filter(Number.isFinite))+1),p={...plot,id:crypto.randomUUID(),number:n,points:stringify(q),labelX:c.x,labelY:c.y};setPlots(v=>[...v,p]);setSelectedPlot(p.id);setDirty(true);}
 function begin(kind:Drag["kind"],id:string,q:Point[],e:React.PointerEvent<SVGElement>,index?:number){e.stopPropagation();setSelectedPlot(kind.startsWith("plot")?id:null);setSelectedSection(kind.startsWith("section")?id:null);setDrag({kind,id,points:q,start:toPoint(e),index});e.currentTarget.setPointerCapture(e.pointerId);}
 function move(e:React.PointerEvent<SVGSVGElement>){if(!drag)return;const n=toPoint(e),dx=n.x-drag.start.x,dy=n.y-drag.start.y;let q=drag.points.map(p=>({x:p.x+dx,y:p.y+dy}));if(drag.kind.endsWith("point")&&drag.index!==undefined)q=drag.points.map((p,i)=>i===drag.index?{x:p.x+dx,y:p.y+dy}:p);if(drag.kind.startsWith("plot")){const c=center(q);setPlots(v=>v.map(p=>p.id===drag.id?{...p,points:stringify(q),labelX:c.x,labelY:c.y}:p));}else setGeo(v=>({...v,[drag.id]:stringify(q)}));setDirty(true);}
 async function upload(kind:"map"|"drone",f:File){setUploading(kind);try{const form=new FormData();form.append("file",f);form.append("planType","master_plan");form.append("kind",kind==="map"?"master-plan":"drone");const r=await fetch(`/api/projects/${encodeURIComponent(projectSlug)}/assets`,{method:"POST",body:form}),d=await r.json();if(!r.ok)throw Error(d.error||"Upload failed");setPlans(v=>v.map(p=>p.id==="master_plan"?{...p,...(kind==="map"?{masterPlanUrl:d.savedValue}:{droneUrl:d.savedValue})}:p));setMessage(`${kind} uploaded`);}catch(e){setMessage(e instanceof Error?e.message:"Upload failed");}finally{setUploading(null);}}
 function updatePlot(k:keyof Plot,v:string){if(!plot)return;setPlots(v=>v.map(p=>p.id===plot.id?{...p,[k]:k==="sectionId"?(v||null):v}:p));setDirty(true);}
 const deselect=()=>{setSelectedPlot(null);setSelectedSection(null);setDrag(null);};
 const zoomPanel=(title:string,value:{x:number;y:number},setValue:(v:{x:number;y:number})=>void)=> <div style={{marginTop:12,padding:10,border:"1px solid #e2e8f0",borderRadius:10,background:"#f8fafc"}}><b style={{fontSize:12}}>{title} Zoom</b><label style={{display:"grid",gridTemplateColumns:"18px 1fr 48px",gap:7,alignItems:"center",fontSize:11,marginTop:8}}><span>↔</span><input aria-label={`${title} horizontal zoom`} type="range" min=".25" max="4" step=".05" value={value.x} onChange={e=>setValue({...value,x:Number(e.target.value)})}/><span>{Math.round(value.x*100)}%</span></label><label style={{display:"grid",gridTemplateColumns:"18px 1fr 48px",gap:7,alignItems:"center",fontSize:11,marginTop:6}}><span>↕</span><input aria-label={`${title} vertical zoom`} type="range" min=".25" max="4" step=".05" value={value.y} onChange={e=>setValue({...value,y:Number(e.target.value)})}/><span>{Math.round(value.y*100)}%</span></label><button type="button" style={{marginTop:7,width:"100%"}} onClick={()=>setValue({x:1,y:1})}>Reset {title}</button></div>;
 const imageTransform=(z:{x:number;y:number})=>`translate(${(1-z.x)*W/2} ${(1-z.y)*H/2}) scale(${z.x} ${z.y})`;
 return <div style={{height:"100vh",display:"grid",gridTemplateRows:"64px 1fr",fontFamily:"Inter,system-ui,sans-serif",background:"#f3f5f8",color:"#172033"}}>
  <header style={{display:"flex",alignItems:"center",justifyContent:"space-between",padding:"0 18px",background:"#fff",borderBottom:"1px solid #e2e8f0"}}><div><small style={{fontWeight:800,color:"#64748b"}}>LANDGRID / EDITOR</small><h2 style={{margin:0,fontSize:20}}>Map & Manage</h2></div><div style={{display:"flex",gap:10,alignItems:"center"}}><span style={{fontSize:12,color:saving?"#b45309":"#15803d"}}>{saving?"Saving…":message||"Saved"}</span><button type="button" onClick={()=>void save()} disabled={!dirty||saving}><Save size={14}/> Save</button></div></header>
  <div style={{display:"grid",gridTemplateColumns:"270px minmax(0,1fr) 300px",minHeight:0}}>
   <aside style={{background:"#fff",padding:12,overflow:"auto",borderRight:"1px solid #e2e8f0"}}><button type="button" onClick={()=>void addSection()} style={{width:"100%",padding:9}}>+ Add Section</button><button type="button" onClick={addPlot} style={{width:"100%",padding:9,marginTop:6}}>+ Add Plot</button><div style={{margin:"18px 0 6px",fontSize:11,fontWeight:800,color:"#64748b"}}>SECTIONS</div><button type="button" onClick={deselect} style={{width:"100%",padding:8,textAlign:"left",background:!selectedSection&&!selectedPlot?"#eef2ff":"#fff"}}>Master Plan</button>{sections.map(s=><div key={s.id} style={{display:"flex",gap:4,marginTop:5}}><button type="button" onClick={()=>{setSelectedSection(s.id);setSelectedPlot(null)}} style={{flex:1,textAlign:"left",padding:8,background:selectedSection===s.id?"#fff7ed":"#fff"}}>{s.name}</button><button type="button" onClick={()=>setConfirm({kind:"section",id:s.id,label:s.name})}><Trash2 size={14}/></button></div>)}<div style={{margin:"18px 0 6px",fontSize:11,fontWeight:800,color:"#64748b"}}>LAYERS</div>{(["drone","map","sections","plots"] as const).map(k=><label key={k} style={{display:"grid",gridTemplateColumns:"70px 1fr",gap:6,alignItems:"center",fontSize:12}}><span>{k[0].toUpperCase()+k.slice(1)}</span><input type="range" min="0" max="1" step=".05" value={opacity[k]} onChange={e=>setOpacity(v=>({...v,[k]:Number(e.target.value)}))}/></label>)}
   <div style={{marginTop:14,borderTop:"1px solid #e2e8f0",paddingTop:12}}><b>Map</b>{zoomPanel("Map",mapZoom,setMapZoom)}<button type="button" onClick={()=>{uploadKind.current="map";fileRef.current?.click()}} style={{width:"100%",marginTop:7,padding:8}}><Upload size={14}/> {uploading==="map"?"Uploading Map…":"Upload Map"}</button></div>
   <div style={{marginTop:14,borderTop:"1px solid #e2e8f0",paddingTop:12}}><b>Drone</b>{zoomPanel("Drone",droneZoom,setDroneZoom)}<button type="button" onClick={()=>{uploadKind.current="drone";fileRef.current?.click()}} style={{width:"100%",marginTop:7,padding:8}}><Upload size={14}/> {uploading==="drone"?"Uploading Drone…":"Upload Drone"}</button><input ref={fileRef} hidden type="file" accept="image/*,.svg" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(uploadKind.current,f);e.currentTarget.value=""}}/></div></aside>
   <main style={{position:"relative",minWidth:0,background:"#dfe4ea"}}><div style={{position:"absolute",zIndex:5,top:10,left:10,right:10,padding:8,background:"rgba(255,255,255,.95)",borderRadius:9,display:"flex",gap:8,alignItems:"center",boxShadow:"0 2px 8px rgba(15,23,42,.08)"}}><span style={{fontSize:12,fontWeight:700}}>4 Layers</span><span style={{fontSize:12,color:"#64748b"}}>Drone → Map → Sections → Plots</span><span style={{marginLeft:"auto",fontSize:12,color:"#64748b"}}>Click empty map to deselect</span></div><svg ref={svgRef} viewBox={`0 0 ${W} ${H}`} preserveAspectRatio="none" onPointerDown={deselect} onPointerMove={move} onPointerUp={()=>setDrag(null)} style={{position:"absolute",inset:0,width:"100%",height:"100%",touchAction:"none"}}>
    {asset("drone")&&<g transform={imageTransform(droneZoom)}><image href={asset("drone")!} width={W} height={H} opacity={opacity.drone} pointerEvents="none"/></g>}
    {asset("map")&&<g transform={imageTransform(mapZoom)}><image href={asset("map")!} width={W} height={H} opacity={opacity.map} pointerEvents="none"/></g>}
    {sections.map(s=>{const q=parse(geo[s.id]||"");if(q.length<3||opacity.sections===0)return null;const active=selectedSection===s.id;return <g key={s.id} opacity={opacity.sections}><polygon points={stringify(q)} fill={active?"rgba(234,88,12,.25)":"rgba(245,158,11,.10)"} stroke={active?"#ea580c":"#f59e0b"} strokeWidth={active?4:2} onPointerDown={e=>begin("section-move",s.id,q,e)}/>{active&&q.map((p,i)=><circle key={i} cx={p.x} cy={p.y} r={10} fill="#fff" stroke="#ea580c" strokeWidth={3} onPointerDown={e=>begin("section-point",s.id,q,e,i)}/>)}</g>})}
    {plots.map(p=>{const q=parse(p.points),active=selectedPlot===p.id;if(q.length<3)return null;return <g key={p.id} opacity={opacity.plots}><polygon points={stringify(q)} fill={active?"rgba(37,99,235,.35)":"rgba(37,99,235,.18)"} stroke={active?"#2563eb":"#3b82f6"} strokeWidth={active?4:2} onPointerDown={e=>begin("plot-move",p.id,q,e)}/>{active&&q.map((pt,i)=><circle key={i} cx={pt.x} cy={pt.y} r={8} fill="#fff" stroke="#2563eb" strokeWidth={3} onPointerDown={e=>begin("plot-point",p.id,q,e,i)}/>) }<text x={p.labelX} y={p.labelY} textAnchor="middle" dominantBaseline="middle" fontSize="22" fontWeight="700" pointerEvents="none">{p.number}</text></g>})}
   </svg></main>
   <aside style={{background:"#fff",padding:16,overflow:"auto",borderLeft:"1px solid #e2e8f0"}}>{plot?<><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><h3 style={{margin:0}}>Plot {plot.number}</h3><button type="button" onClick={deselect}>×</button></div><label>Section<select value={plot.sectionId??""} onChange={e=>updatePlot("sectionId",e.target.value)}><option value="">Master Plan / Unassigned</option>{sections.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>{(["status","owner","price","area","direction","model"] as const).map(k=><label key={k} style={{display:"block",marginTop:10,textTransform:"capitalize"}}>{k}<input value={String(plot[k]??"")} onChange={e=>updatePlot(k,e.target.value)}/></label>)}<div style={{display:"flex",gap:7,marginTop:14}}><button type="button" onClick={duplicatePlot}><Copy size={14}/> Duplicate</button><button type="button" onClick={()=>setConfirm({kind:"plot",id:plot.id,label:`Plot ${plot.number}`})}><Trash2 size={14}/> Delete</button></div></>:selectedSection?<><h3>{sections.find(s=>s.id===selectedSection)?.name}</h3><p>Drag the center to move the section. Drag each vertex to reshape it.</p></>:<div style={{color:"#64748b"}}>Select a plot or section to edit its details.</div>}</aside>
  </div>
  {confirm&&<div style={{position:"fixed",inset:0,background:"rgba(15,23,42,.45)",display:"grid",placeItems:"center",zIndex:50}}><div style={{background:"#fff",padding:22,borderRadius:12,width:360,boxShadow:"0 20px 60px rgba(0,0,0,.2)"}}><h3>Confirm deletion</h3><p>Delete {confirm.label}? {confirm.kind==="section"?"Plots will be preserved.":"This plot will be removed."}</p><div style={{display:"flex",justifyContent:"flex-end",gap:8}}><button type="button" onClick={()=>setConfirm(null)}>Cancel</button><button type="button" onClick={()=>{if(confirm.kind==="section")void deleteSection(confirm.id);else{setPlots(v=>v.filter(p=>p.id!==confirm.id));setSelectedPlot(null);setConfirm(null);setDirty(true);}}}>Delete</button></div></div></div>}
 </div>;
}
