'use client';

import { useEffect, useMemo, useState } from 'react';

type Props = { projectName: string; projectSlug?: string; sitePlanUrl?: string | null; droneUrl?: string | null };
type Section = { id: string; name: string; sortOrder: number; masterPlanUrl?: string | null; droneUrl?: string | null };
type Lot = { id: string; number: string; status: string; owner: string; price: number | string | null; area: number | string | null; direction: string; points: string; labelX: number; labelY: number; sectionId?: string | null };
type Point = { x: number; y: number };
function parsePoints(value: string): Point[] { return value.trim().split(/\s+/).map(p => p.split(',').map(Number)).filter(p => Number.isFinite(p[0]) && Number.isFinite(p[1])).map(([x,y]) => ({x,y})); }
function bounds(lots: Lot[]) { const pts=lots.flatMap(l=>parsePoints(l.points)); if(!pts.length)return {minX:0,minY:0,maxX:1600,maxY:1000}; return {minX:Math.min(...pts.map(p=>p.x)),minY:Math.min(...pts.map(p=>p.y)),maxX:Math.max(...pts.map(p=>p.x)),maxY:Math.max(...pts.map(p=>p.y))}; }

export default function ProjectPlanViewer({ projectName, projectSlug, sitePlanUrl, droneUrl }: Props) {
  const [view,setView]=useState<'map'|'drone'>('map'); const [sections,setSections]=useState<Section[]>([]); const [lots,setLots]=useState<Lot[]>([]); const [sectionId,setSectionId]=useState(''); const [loading,setLoading]=useState(Boolean(projectSlug)); const [error,setError]=useState(''); const [selected,setSelected]=useState<string|null>(null);
  useEffect(()=>{if(!projectSlug){setLoading(false);return;}let active=true;fetch(`/api/projects/${encodeURIComponent(projectSlug)}/plan`,{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to load plan');return d;}).then(d=>{if(!active)return;setSections(d.sections||[]);setLots(d.lots||[]);if(d.sections?.[0])setSectionId(d.sections[0].id);}).catch(e=>active&&setError(e instanceof Error?e.message:'Unable to load plan')).finally(()=>active&&setLoading(false));return()=>{active=false};},[projectSlug]);
  const current=sections.find(s=>s.id===sectionId)||sections[0]; const sectionLots=useMemo(()=>lots.filter(l=>(l.sectionId||sectionId)===sectionId),[lots,sectionId]); const b=useMemo(()=>bounds(sectionLots),[sectionLots]); const viewBox=`${b.minX-100} ${b.minY-100} ${Math.max(1,b.maxX-b.minX+200)} ${Math.max(1,b.maxY-b.minY+200)}`;
  const imageUrl=projectSlug&&current?(view==='map'?(current.masterPlanUrl?`/api/projects/${encodeURIComponent(projectSlug)}/assets/file?kind=section-master-plan&section=${current.id}`:''):(current.droneUrl?`/api/projects/${encodeURIComponent(projectSlug)}/assets/file?kind=section-drone&section=${current.id}`:'')):(!projectSlug?(view==='map'?sitePlanUrl||'':droneUrl||''):'');
  if(loading)return <div className="map-placeholder" style={{minHeight:520,display:'grid',placeItems:'center'}}>Loading project plan…</div>;
  return <div style={{display:'grid',gap:16}}><div className="map-placeholder" style={{minHeight:520,position:'relative',overflow:'hidden',background:'#eef0f3'}}>
    <div style={{position:'absolute',top:12,left:12,right:12,zIndex:4,display:'flex',justifyContent:'space-between',alignItems:'center',gap:12}}><div style={{display:'flex',alignItems:'center',gap:8,background:'rgba(255,255,255,.96)',padding:'6px 10px',borderRadius:9}}><span className="eyebrow">PLAN</span><select value={sectionId} onChange={e=>{setSectionId(e.target.value);setSelected(null);}}>{sections.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></div><div style={{display:'flex',gap:4,background:'rgba(255,255,255,.96)',padding:4,borderRadius:10,boxShadow:'0 2px 10px rgba(0,0,0,.08)'}}><button type="button" onClick={()=>setView('map')} style={{border:0,borderRadius:7,padding:'8px 14px',fontWeight:700,color:view==='map'?'#fff':'#1f2937',background:view==='map'?'#111827':'transparent'}}>Map</button><button type="button" onClick={()=>setView('drone')} style={{border:0,borderRadius:7,padding:'8px 14px',fontWeight:700,color:view==='drone'?'#fff':'#1f2937',background:view==='drone'?'#111827':'transparent'}}>Drone</button></div></div>
    {imageUrl?<img src={imageUrl} alt={`${projectName} ${current?.name||'plan'} ${view}`} style={{position:'absolute',left:0,right:0,bottom:0,top:52,width:'100%',height:'calc(100% - 52px)',objectFit:'fill'}}/>:<div className="map-copy" style={{minHeight:520,display:'grid',placeItems:'center',padding:32,textAlign:'center'}}>{view==='map'?'Add a map for this section.':'Add a drone image for this section.'}</div>}
    <svg viewBox={viewBox} preserveAspectRatio="none" style={{position:'absolute',left:0,right:0,bottom:0,top:52,width:'100%',height:'calc(100% - 52px)'}}>{sectionLots.map(lot=>{const active=selected===lot.id;return <g key={lot.id} onClick={()=>setSelected(lot.id)} style={{cursor:'pointer'}}><polygon points={lot.points} fill={active?'rgba(37,99,235,.35)':'rgba(37,99,235,.12)'} stroke={active?'#2457d6':'#fff'} strokeWidth={active?4:2}/><text x={lot.labelX} y={lot.labelY} textAnchor="middle" dominantBaseline="middle" fontSize="24" fontWeight="800" fill="#172033" paintOrder="stroke" stroke="#fff" strokeWidth="5">{lot.number}</text></g>})}</svg>
    <div style={{position:'absolute',bottom:12,left:12,background:'rgba(255,255,255,.94)',borderRadius:9,padding:'7px 10px',fontSize:12,fontWeight:700}}>{current?.name||'Master'} · {sectionLots.length} lots</div>{error&&<div style={{position:'absolute',left:16,bottom:16,right:16,zIndex:5,padding:10,borderRadius:8,background:'#fff1f2',color:'#991b1b',fontSize:13}}>{error}</div>}
  </div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(180px,1fr))',gap:8}}>{sectionLots.map(lot=><button key={lot.id} onClick={()=>setSelected(lot.id)} style={{textAlign:'left',padding:'10px 12px',border:'1px solid #e4e7ec',borderRadius:9,background:selected===lot.id?'#eef2ff':'#fff',cursor:'pointer'}}><b>Lot {lot.number}</b><div style={{fontSize:11,color:'#667085',marginTop:3,textTransform:'capitalize'}}>{lot.status}{lot.owner?` · ${lot.owner}`:''}</div></button>)}</div></div>;
}
